accounts:
  - name: 'far-CallRatioSpread'
    trades:
      - date: 2022-01-10 
        symbol: C3M3
        direction: L 
        volume: 30
      - date: 2022-01-10  
        symbol: C6M3
        direction: S 
        volume: 20
      - date: 2022-01-10 
        symbol: C7M3
        direction: S
        volume: 20
  - name: 'near-CallRatioSpread'
    trades:
      - name: primary
        date: 2022-01-10  
        symbol: C3M2
        direction: L 
        volume: 30
        closePolicy:
          - type: pl
            expression: '$>0.5'
      - date: 2022-01-10 
        symbol: C6M2
        direction: S 
        volume: 20
        # closePolicy is expected to be set at position opening, 
        # as it defines when the position should be closed.
        closePolicy:
          - type: pl
            expression: '$>0.8'
          - type: linked
            position: primary
            'on': close
      - date: 2022-01-10  
        symbol: C7M2
        direction: S
        volume: 20
        closePolicy:
          - type: pl
            expression: '$>0.8'
          - type: linked
            position: primary
            'on': close
  - name: relay-callspread
    start: 2022-03-25
    strategy:
      name: relay
      template:
        - name: primary
          symbol: C6M1
          direction: L
          triggers:
            - type: price
              expression: '$<=0.03'
          volume: 20
          closePolicy:
            - type: pl
              expression: '$>1.0'
        - name: affliated
          symbol: C7M1
          direction: S
          triggers:
            - type: linked
              position: primary
              on: open
          volume: 30
          closePolicy:
            - type: pl
              expression: '$>0.8'
            - type: linked
              position: primary
              on: close
